"""
US Stock Scanner - 미국주식 스캐너.

KIS API 또는 인기 종목 리스트를 활용한 미국주식 스캐닝.
"""

import logging
import random
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


POPULAR_US_STOCKS = [
    {"symbol": "AAPL", "name": "Apple Inc.", "exchange": "NASD"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "exchange": "NASD"},
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "exchange": "NASD"},
    {"symbol": "GOOG", "name": "Alphabet Inc. Class C", "exchange": "NASD"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "exchange": "NASD"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "exchange": "NASD"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "exchange": "NASD"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "exchange": "NASD"},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway", "exchange": "NASD"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "exchange": "NYSE"},
    {"symbol": "V", "name": "Visa Inc.", "exchange": "NYSE"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "exchange": "NYSE"},
    {"symbol": "WMT", "name": "Walmart Inc.", "exchange": "NYSE"},
    {"symbol": "PG", "name": "Procter & Gamble", "exchange": "NYSE"},
    {"symbol": "MA", "name": "Mastercard Inc.", "exchange": "NASD"},
    {"symbol": "UNH", "name": "UnitedHealth Group", "exchange": "NYSE"},
    {"symbol": "HD", "name": "Home Depot Inc.", "exchange": "NYSE"},
    {"symbol": "DIS", "name": "Walt Disney Company", "exchange": "NYSE"},
    {"symbol": "BAC", "name": "Bank of America", "exchange": "NYSE"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "exchange": "NASD"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "exchange": "NYSE"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "exchange": "NASD"},
    {"symbol": "XOM", "name": "Exxon Mobil", "exchange": "NYSE"},
    {"symbol": "COST", "name": "Costco Wholesale", "exchange": "NASD"},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "exchange": "NASD"},
    {"symbol": "INTC", "name": "Intel Corporation", "exchange": "NASD"},
    {"symbol": "CSCO", "name": "Cisco Systems", "exchange": "NASD"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "exchange": "NASD"},
    {"symbol": "KO", "name": "Coca-Cola Company", "exchange": "NYSE"},
    {"symbol": "NKE", "name": "Nike Inc.", "exchange": "NYSE"},
    {"symbol": "MRK", "name": "Merck & Co.", "exchange": "NYSE"},
    {"symbol": "CVX", "name": "Chevron Corporation", "exchange": "NYSE"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "exchange": "NYSE"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "exchange": "NYSE"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "exchange": "NYSE"},
    {"symbol": "ACN", "name": "Accenture plc", "exchange": "NYSE"},
    {"symbol": "TXN", "name": "Texas Instruments", "exchange": "NASD"},
    {"symbol": "QCOM", "name": "QUALCOMM Inc.", "exchange": "NASD"},
    {"symbol": "IBM", "name": "IBM Corporation", "exchange": "NYSE"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "exchange": "NASD"},
    {"symbol": "INTU", "name": "Intuit Inc.", "exchange": "NASD"},
    {"symbol": "AMAT", "name": "Applied Materials", "exchange": "NASD"},
    {"symbol": "BKNG", "name": "Booking Holdings", "exchange": "NASD"},
    {"symbol": "ISRG", "name": "Intuitive Surgical", "exchange": "NASD"},
    {"symbol": "GILD", "name": "Gilead Sciences", "exchange": "NASD"},
    {"symbol": "ADP", "name": "Automatic Data Processing", "exchange": "NASD"},
    {"symbol": "MDLZ", "name": "Mondelez International", "exchange": "NASD"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals", "exchange": "NASD"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals", "exchange": "NASD"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "exchange": "NYSE"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "exchange": "NASD"},
    {"symbol": "TMUS", "name": "T-Mobile US", "exchange": "NASD"},
    {"symbol": "MU", "name": "Micron Technology", "exchange": "NASD"},
    {"symbol": "SNAP", "name": "Snap Inc.", "exchange": "NASD"},
    {"symbol": "PYPL", "name": "PayPal Holdings", "exchange": "NASD"},
    {"symbol": "UBER", "name": "Uber Technologies", "exchange": "NASD"},
    {"symbol": "ABNB", "name": "Airbnb Inc.", "exchange": "NASD"},
    {"symbol": "SQ", "name": "Block Inc.", "exchange": "NASD"},
    {"symbol": "SHOP", "name": "Shopify Inc.", "exchange": "NASD"},
    {"symbol": "SPOT", "name": "Spotify Technology", "exchange": "NASD"},
    {"symbol": "ROKU", "name": "Roku Inc.", "exchange": "NASD"},
    {"symbol": "CRWD", "name": "CrowdStrike Holdings", "exchange": "NASD"},
    {"symbol": "DDOG", "name": "Datadog Inc.", "exchange": "NASD"},
    {"symbol": "NET", "name": "Cloudflare Inc.", "exchange": "NASD"},
    {"symbol": "SNOW", "name": "Snowflake Inc.", "exchange": "NASD"},
    {"symbol": "PLTR", "name": "Palantir Technologies", "exchange": "NASD"},
    {"symbol": "ARM", "name": "Arm Holdings", "exchange": "NASD"},
    {"symbol": "MARA", "name": "Marathon Digital Holdings", "exchange": "NASD"},
    {"symbol": "RIOT", "name": "Riot Platforms", "exchange": "NASD"},
    {"symbol": "COIN", "name": "Coinbase Global", "exchange": "NASD"},
    {"symbol": "SPY", "name": "SPDR S&P 500 ETF Trust", "exchange": "NASD"},
    {"symbol": "QQQ", "name": "Invesco QQQ Trust", "exchange": "NASD"},
    {"symbol": "IWM", "name": "iShares Russell 2000 ETF", "exchange": "NASD"},
    {"symbol": "DIA", "name": "SPDR Dow Jones ETF", "exchange": "NASD"},
    {"symbol": "EEM", "name": "iShares MSCI Emerging Markets", "exchange": "NASD"},
    {"symbol": "EWJ", "name": "iShares MSCI Japan", "exchange": "NASD"},
    {"symbol": "EWZ", "name": "iShares MSCI Brazil", "exchange": "NASD"},
    {"symbol": "EWG", "name": "iShares MSCI Germany", "exchange": "NASD"},
    {"symbol": "EWU", "name": "iShares MSCI United Kingdom", "exchange": "NASD"},
    {"symbol": "EWY", "name": "iShares MSCI South Korea", "exchange": "NASD"},
    {"symbol": "FXI", "name": "iShares MSCI China", "exchange": "NASD"},
    {"symbol": "SMH", "name": "VanEck Semiconductor ETF", "exchange": "NASD"},
    {"symbol": "SOXX", "name": "iShares Semiconductor ETF", "exchange": "NASD"},
    {"symbol": "XLF", "name": "Financial Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLE", "name": "Energy Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLV", "name": "Health Care Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLI", "name": "Industrial Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLC", "name": "Communication Services Select SPDR", "exchange": "NASD"},
    {"symbol": "XLY", "name": "Consumer Discretionary Select SPDR", "exchange": "NASD"},
    {"symbol": "XLP", "name": "Consumer Staples Select SPDR", "exchange": "NASD"},
    {"symbol": "XLK", "name": "Technology Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLB", "name": "Materials Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLRE", "name": "Real Estate Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLU", "name": "Utilities Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "XLC", "name": "Communication Services SPDR", "exchange": "NASD"},
    {"symbol": "SSO", "name": "ProShares Ultra S&P 500 (2x)", "exchange": "NASD"},
    {
        "symbol": "SPXL",
        "name": "Direxion Daily S&P 500 Bull 3x (3x)",
        "exchange": "NASD",
    },
    {"symbol": "UPRO", "name": "ProShares UltraPro S&P 500 (3x)", "exchange": "NASD"},
    {"symbol": "SDS", "name": "ProShares UltraShort S&P 500 (-2x)", "exchange": "NASD"},
    {
        "symbol": "SPXU",
        "name": "ProShares UltraShort S&P 500 (-3x)",
        "exchange": "NASD",
    },
    {"symbol": "SH", "name": "ProShares Short S&P 500 (-1x)", "exchange": "NASD"},
    {"symbol": "QLD", "name": "ProShares Ultra QQQ (2x)", "exchange": "NASD"},
    {"symbol": "TQQQ", "name": "ProShares UltraPro QQQ (3x)", "exchange": "NASD"},
    {"symbol": "QID", "name": "ProShares UltraShort QQQ (-2x)", "exchange": "NASD"},
    {"symbol": "SQQQ", "name": "ProShares UltraShort QQQ (-3x)", "exchange": "NASD"},
    {"symbol": "PSQ", "name": "ProShares Short QQQ (-1x)", "exchange": "NASD"},
    {"symbol": "DDM", "name": "ProShares Ultra Dow30 (2x)", "exchange": "NASD"},
    {"symbol": "UDOW", "name": "Direxion Daily Dow30 Bull 3x (3x)", "exchange": "NASD"},
    {"symbol": "SDOW", "name": "ProShares UltraShort Dow30 (-2x)", "exchange": "NASD"},
    {"symbol": "DOG", "name": "ProShares Short Dow30 (-1x)", "exchange": "NASD"},
    {"symbol": "UWM", "name": "ProShares Ultra Russell2000 (2x)", "exchange": "NASD"},
    {
        "symbol": "URTY",
        "name": "ProShares UltraPro Russell2000 (3x)",
        "exchange": "NASD",
    },
    {
        "symbol": "TWM",
        "name": "ProShares UltraShort Russell2000 (-2x)",
        "exchange": "NASD",
    },
    {"symbol": "RWM", "name": "ProShares Short Russell2000 (-1x)", "exchange": "NASD"},
    {
        "symbol": "SOXL",
        "name": "Direxion Daily Semiconductor Bull 3x",
        "exchange": "NASD",
    },
    {
        "symbol": "SOXS",
        "name": "Direxion Daily Semiconductor Bear 3x",
        "exchange": "NASD",
    },
    {"symbol": "FAS", "name": "Direxion Daily Financial Bull 3x", "exchange": "NASD"},
    {"symbol": "FAZ", "name": "Direxion Daily Financial Bear 3x", "exchange": "NASD"},
    {"symbol": "XLE", "name": "Energy Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "ERX", "name": "Direxion Daily Energy Bull 3x", "exchange": "NASD"},
    {"symbol": "ERY", "name": "Direxion Daily Energy Bear 3x", "exchange": "NASD"},
    {"symbol": "XLF", "name": "Financial Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "FINU", "name": "ProShares Ultra Financials (2x)", "exchange": "NASD"},
    {
        "symbol": "FINZ",
        "name": "ProShares UltraShort Financials (-2x)",
        "exchange": "NASD",
    },
    {"symbol": "XLV", "name": "Health Care Select Sector SPDR", "exchange": "NASD"},
    {
        "symbol": "CURE",
        "name": "Direxion Daily Health Care Bull 3x",
        "exchange": "NASD",
    },
    {
        "symbol": "LABD",
        "name": "Direxion Daily Health Care Bear 3x",
        "exchange": "NASD",
    },
    {"symbol": "XLI", "name": "Industrial Select Sector SPDR", "exchange": "NASD"},
    {"symbol": "FNG", "name": "Direxion Daily MSCI USA Bull 3x", "exchange": "NASD"},
    {
        "symbol": "EDC",
        "name": "Direxion Daily Emerging Markets Bull 3x",
        "exchange": "NASD",
    },
    {
        "symbol": "EDZ",
        "name": "Direxion Daily Emerging Markets Bear 3x",
        "exchange": "NASD",
    },
    {
        "symbol": "KORU",
        "name": "Direxion Daily South Korea Bull 3x",
        "exchange": "NASD",
    },
    {"symbol": "CHAU", "name": "Direxion Daily China Bull 3x", "exchange": "NASD"},
    {"symbol": "CNYD", "name": "Direxion Daily China Bear 3x", "exchange": "NASD"},
    {"symbol": "JPXN", "name": "iShares JPX-Nikkei 400", "exchange": "NASD"},
    {"symbol": "EWV", "name": "iShares MSCI Japan Value", "exchange": "NASD"},
    {"symbol": "EWJ", "name": "iShares MSCI Japan", "exchange": "NASD"},
    {"symbol": "DXJ", "name": "WisdomTree Japan Hedged Equity", "exchange": "NASD"},
    {"symbol": "FLJP", "name": "Franklin Templeton Japan", "exchange": "NASD"},
    {"symbol": "EWZ", "name": "iShares MSCI Brazil", "exchange": "NASD"},
    {"symbol": "Braz", "name": "Franklin Brazil Equity", "exchange": "NASD"},
    {"symbol": "EWG", "name": "iShares MSCI Germany", "exchange": "NASD"},
    {"symbol": "EWU", "name": "iShares MSCI United Kingdom", "exchange": "NASD"},
    {"symbol": "EWI", "name": "iShares MSCI Italy", "exchange": "NASD"},
    {"symbol": "EWP", "name": "iShares MSCI Spain", "exchange": "NASD"},
    {"symbol": "EWN", "name": "iShares MSCI Netherlands", "exchange": "NASD"},
    {"symbol": "EWL", "name": "iShares MSCI Switzerland", "exchange": "NASD"},
    {"symbol": "EWQ", "name": "iShares MSCI France", "exchange": "NASD"},
    {"symbol": "EFA", "name": "iShares MSCI EAFE", "exchange": "NASD"},
    {"symbol": "IEFA", "name": "iShares Core MSCI EAFE", "exchange": "NASD"},
    {"symbol": "VEA", "name": "Vanguard FTSE Developed Markets", "exchange": "NASD"},
    {"symbol": "VWO", "name": "Vanguard FTSE Emerging Markets", "exchange": "NASD"},
    {"symbol": "IEMG", "name": "iShares Core MSCI Emerging", "exchange": "NASD"},
    {"symbol": "SCHE", "name": "Schwab Emerging Markets Equity", "exchange": "NASD"},
    {"symbol": "SCHF", "name": "Schwab International Equity", "exchange": "NASD"},
    {"symbol": "SPDW", "name": "SPDR Developed World ex-US", "exchange": "NASD"},
    {"symbol": "SPEM", "name": "SPDR Emerging Markets", "exchange": "NASD"},
    {"symbol": "GSG", "name": "iShares GSCI Commodity", "exchange": "NASD"},
    {"symbol": "DBC", "name": "Invesco DB Commodity Tracking", "exchange": "NASD"},
    {"symbol": "GLD", "name": "SPDR Gold Shares", "exchange": "NASD"},
    {"symbol": "SLV", "name": "iShares Silver Trust", "exchange": "NASD"},
    {"symbol": "USO", "name": "United States Oil Fund", "exchange": "NASD"},
    {"symbol": "UNG", "name": "United States Natural Gas Fund", "exchange": "NASD"},
    {"symbol": "CORN", "name": "Teucrium Corn Fund", "exchange": "NASD"},
    {"symbol": "WEAT", "name": "Teucrium Wheat Fund", "exchange": "NASD"},
    {"symbol": "SOYB", "name": "Teucrium Soybean Fund", "exchange": "NASD"},
    {"symbol": "VIXM", "name": "ProShares VIX Mid-Term Futures", "exchange": "NASD"},
    {"symbol": "VIXY", "name": "ProShares VIX Short-Term Futures", "exchange": "NASD"},
    {"symbol": "TVIX", "name": "VelocityShares Daily 2x VIX Short", "exchange": "NASD"},
    {
        "symbol": "UVXY",
        "name": "ProShares Ultra VIX Short-Term Futures",
        "exchange": "NASD",
    },
    {
        "symbol": "SVXY",
        "name": "ProShares Short VIX Short-Term Futures",
        "exchange": "NASD",
    },
    {
        "symbol": "XIV",
        "name": "VelocityShares Daily Inverse VIX Short",
        "exchange": "NASD",
    },
    {"symbol": "ZL", "name": "VelocityShares Long 2x VIX", "exchange": "NASD"},
    {"symbol": "VOX", "name": "Vanguard Communication Services", "exchange": "NASD"},
    {"symbol": "VCR", "name": "Vanguard Consumer Discretionary", "exchange": "NASD"},
    {"symbol": "VDC", "name": "Vanguard Consumer Staples", "exchange": "NASD"},
    {"symbol": "VDE", "name": "Vanguard Energy", "exchange": "NASD"},
    {"symbol": "VFH", "name": "Vanguard Financials", "exchange": "NASD"},
    {"symbol": "VHT", "name": "Vanguard Health Care", "exchange": "NASD"},
    {"symbol": "VIG", "name": "Vanguard Dividend Appreciation", "exchange": "NASD"},
    {"symbol": "VYM", "name": "Vanguard High Dividend Yield", "exchange": "NASD"},
    {"symbol": "VTV", "name": "Vanguard Value ETF", "exchange": "NASD"},
    {"symbol": "VUG", "name": "Vanguard Growth ETF", "exchange": "NASD"},
    {"symbol": "VVO", "name": "Vanguard Mid-Cap Value", "exchange": "NASD"},
    {"symbol": "VB", "name": "Vanguard Small-Cap ETF", "exchange": "NASD"},
    {"symbol": "IJH", "name": "iShares Core S&P Mid-Cap", "exchange": "NASD"},
    {"symbol": "IJR", "name": "iShares Core S&P Small-Cap", "exchange": "NASD"},
    {"symbol": "MDY", "name": "SPDR S&P MidCap 400", "exchange": "NASD"},
    {"symbol": "SPLG", "name": "SPDR Portfolio S&P 500", "exchange": "NASD"},
    {"symbol": "SCHD", "name": "Schwab US Dividend Equity", "exchange": "NASD"},
    {"symbol": "DGRO", "name": "iShares Dividend Growth", "exchange": "NASD"},
    {"symbol": "VIGI", "name": "Vanguard International Dividend", "exchange": "NASD"},
    {"symbol": "DVY", "name": "iShares Select Dividend", "exchange": "NASD"},
    {"symbol": "HDV", "name": "iShares Core High Dividend", "exchange": "NASD"},
    {"symbol": "SPHD", "name": "SPDR S&P High Dividend", "exchange": "NASD"},
    {"symbol": "STAG", "name": "STAG Industrial", "exchange": "NASD"},
    {"symbol": "O", "name": "Realty Income Corporation", "exchange": "NASD"},
    {"symbol": "AMT", "name": "American Tower Corporation", "exchange": "NASD"},
    {"symbol": "PLD", "name": "Prologis Inc.", "exchange": "NASD"},
    {"symbol": "EQIX", "name": "Equinix Inc.", "exchange": "NASD"},
    {"symbol": "PSA", "name": "Public Storage", "exchange": "NASD"},
    {"symbol": "SPG", "name": "Simon Property Group", "exchange": "NASD"},
    {"symbol": "WELL", "name": "Welltower Inc.", "exchange": "NASD"},
    {"symbol": "VNO", "name": "Vornado Realty Trust", "exchange": "NASD"},
    {"symbol": "SLB", "name": "Schlumberger Limited", "exchange": "NASD"},
    {"symbol": "EOG", "name": "EOG Resources Inc.", "exchange": "NASD"},
    {"symbol": "MPC", "name": "Marathon Petroleum", "exchange": "NASD"},
    {"symbol": "PSX", "name": "Phillips 66", "exchange": "NASD"},
    {"symbol": "VLO", "name": "Valero Energy", "exchange": "NASD"},
    {"symbol": "OXY", "name": "Occidental Petroleum", "exchange": "NASD"},
    {"symbol": "HAL", "name": "Halliburton Company", "exchange": "NASD"},
    {"symbol": "BKR", "name": "Baker Hughes Company", "exchange": "NASD"},
    {"symbol": "DVN", "name": "Devon Energy Corporation", "exchange": "NASD"},
    {"symbol": "FANG", "name": "Diamondback Energy", "exchange": "NASD"},
    {"symbol": "PXD", "name": "Pioneer Natural Resources", "exchange": "NASD"},
    {"symbol": "APA", "name": "APA Corporation", "exchange": "NASD"},
    {"symbol": "COP", "name": "ConocoPhillips", "exchange": "NASD"},
    {"symbol": "MET", "name": "MetLife Inc.", "exchange": "NASD"},
    {"symbol": "PRU", "name": "Prudential Financial", "exchange": "NASD"},
    {"symbol": "AFL", "name": "Aflac Incorporated", "exchange": "NASD"},
    {"symbol": "TRV", "name": "Travelers Companies", "exchange": "NASD"},
    {"symbol": "ALL", "name": "Allstate Corporation", "exchange": "NASD"},
    {"symbol": "C", "name": "Citigroup Inc.", "exchange": "NASD"},
    {"symbol": "GS", "name": "Goldman Sachs Group", "exchange": "NASD"},
    {"symbol": "MS", "name": "Morgan Stanley", "exchange": "NASD"},
    {"symbol": "BLK", "name": "BlackRock Inc.", "exchange": "NASD"},
    {"symbol": "SCHW", "name": "Charles Schwab Corporation", "exchange": "NASD"},
    {"symbol": "AXP", "name": "American Express Company", "exchange": "NASD"},
    {"symbol": "DFS", "name": "Discover Financial Services", "exchange": "NASD"},
    {"symbol": "SYF", "name": "Synchrony Financial", "exchange": "NASD"},
    {"symbol": "USB", "name": "US Bancorp", "exchange": "NASD"},
    {"symbol": "PNC", "name": "PNC Financial Services", "exchange": "NASD"},
    {"symbol": "TFC", "name": "Truist Financial Corporation", "exchange": "NASD"},
    {"symbol": "COF", "name": "Capital One Financial", "exchange": "NASD"},
    {"symbol": "WFC", "name": "Wells Fargo & Company", "exchange": "NASD"},
    {"symbol": "USB", "name": "U.S. Bancorp", "exchange": "NASD"},
    {"symbol": "NEE", "name": "NextEra Energy Inc.", "exchange": "NASD"},
    {"symbol": "DUK", "name": "Duke Energy Corporation", "exchange": "NASD"},
    {"symbol": "SO", "name": "Southern Company", "exchange": "NASD"},
    {"symbol": "D", "name": "Dominion Energy Inc.", "exchange": "NASD"},
    {"symbol": "AEP", "name": "American Electric Power", "exchange": "NASD"},
    {"symbol": "SRE", "name": "Sempra Energy", "exchange": "NASD"},
    {"symbol": "DOW", "name": "Dow Inc.", "exchange": "NASD"},
    {"symbol": "LIN", "name": "Linde plc", "exchange": "NASD"},
    {"symbol": "APD", "name": "Air Products and Chemicals", "exchange": "NASD"},
    {"symbol": "ECL", "name": "Ecolab Inc.", "exchange": "NASD"},
    {"symbol": "SHW", "name": "Sherwin-Williams Company", "exchange": "NASD"},
    {"symbol": "FCX", "name": "Freeport-McMoRan Inc.", "exchange": "NASD"},
    {"symbol": "NEM", "name": "Newmont Corporation", "exchange": "NASD"},
    {"symbol": "AA", "name": "Alcoa Corporation", "exchange": "NASD"},
    {"symbol": "NUE", "name": "Nucor Corporation", "exchange": "NASD"},
    {"symbol": "X", "name": "United States Steel Corporation", "exchange": "NASD"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "exchange": "NASD"},
    {"symbol": "DE", "name": "Deere & Company", "exchange": "NASD"},
    {"symbol": "BA", "name": "Boeing Company", "exchange": "NASD"},
    {"symbol": "HON", "name": "Honeywell International", "exchange": "NASD"},
    {"symbol": "UPS", "name": "United Parcel Service", "exchange": "NASD"},
    {"symbol": "RTX", "name": "RTX Corporation", "exchange": "NASD"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "exchange": "NASD"},
    {"symbol": "GE", "name": "General Electric Company", "exchange": "NASD"},
    {"symbol": "MMM", "name": "3M Company", "exchange": "NASD"},
    {"symbol": "EMR", "name": "Emerson Electric Co.", "exchange": "NASD"},
    {"symbol": "FDX", "name": "FedEx Corporation", "exchange": "NASD"},
    {"symbol": "ITW", "name": "Illinois Tool Works", "exchange": "NASD"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "exchange": "NASD"},
    {"symbol": "PH", "name": "Parker-Hannifin Corporation", "exchange": "NASD"},
    {"symbol": "ROK", "name": "Rockwell Automation", "exchange": "NASD"},
    {"symbol": "CMI", "name": "Cummins Inc.", "exchange": "NASD"},
    {"symbol": "PCAR", "name": "PACCAR Inc.", "exchange": "NASD"},
    {"symbol": "WM", "name": "Waste Management Inc.", "exchange": "NASD"},
    {"symbol": "RSG", "name": "Republic Services Inc.", "exchange": "NASD"},
    {"symbol": "FAST", "name": "Fastenal Company", "exchange": "NASD"},
    {"symbol": "CARR", "name": "Carrier Global Corporation", "exchange": "NASD"},
    {"symbol": "ODFL", "name": "Old Dominion Freight Line", "exchange": "NASD"},
    {"symbol": "PAYX", "name": "Paychex Inc.", "exchange": "NASD"},
    {"symbol": "INTU", "name": "Intuit Inc.", "exchange": "NASD"},
    {"symbol": "ADP", "name": "Automatic Data Processing", "exchange": "NASD"},
    {"symbol": "PAYC", "name": "Paycom Software Inc.", "exchange": "NASD"},
    {"symbol": "HRL", "name": "Hormel Foods Corporation", "exchange": "NASD"},
    {"symbol": "KMB", "name": "Kimberly-Clark Corporation", "exchange": "NASD"},
    {"symbol": "CL", "name": "Colgate-Palmolive Company", "exchange": "NASD"},
    {"symbol": "GIS", "name": "General Mills Inc.", "exchange": "NASD"},
    {"symbol": "MDLZ", "name": "Mondelez International", "exchange": "NASD"},
    {"symbol": "K", "name": "Kellogg Company", "exchange": "NASD"},
    {"symbol": "HSY", "name": "Hershey Company", "exchange": "NASD"},
    {"symbol": "STZ", "name": "Constellation Brands Inc.", "exchange": "NASD"},
    {"symbol": "MO", "name": "Altria Group Inc.", "exchange": "NASD"},
    {"symbol": "PM", "name": "Philip Morris International", "exchange": "NASD"},
    {"symbol": "BTI", "name": "British American Tobacco", "exchange": "NASD"},
    {"symbol": "CVS", "name": "CVS Health Corporation", "exchange": "NASD"},
    {"symbol": "WBA", "name": "Walgreens Boots Alliance", "exchange": "NASD"},
    {"symbol": "CI", "name": "Cigna Group", "exchange": "NASD"},
    {"symbol": "HUM", "name": "Humana Inc.", "exchange": "NASD"},
    {"symbol": "ANTM", "name": "Anthem Inc.", "exchange": "NASD"},
    {"symbol": "MOH", "name": "Molina Healthcare Inc.", "exchange": "NASD"},
    {"symbol": "CNC", "name": "Centene Corporation", "exchange": "NASD"},
    {"symbol": "UNH", "name": "UnitedHealth Group", "exchange": "NASD"},
    {"symbol": "EL", "name": "Estee Lauder Companies", "exchange": "NASD"},
    {"symbol": "PG", "name": "Procter & Gamble Company", "exchange": "NASD"},
    {"symbol": "CLX", "name": "Clorox Company", "exchange": "NASD"},
    {"symbol": "KMB", "name": "Kimberly-Clark Corporation", "exchange": "NASD"},
    {"symbol": "CHRW", "name": "C.H. Robinson Worldwide", "exchange": "NASD"},
    {"symbol": "EXPD", "name": "Expeditors International", "exchange": "NASD"},
    {"symbol": "FIS", "name": "Fidelity National Information", "exchange": "NASD"},
    {"symbol": "FISV", "name": "Fiserv Inc.", "exchange": "NASD"},
    {"symbol": "GPN", "name": "Global Payments Inc.", "exchange": "NASD"},
    {"symbol": "PAYX", "name": "Paychex Inc.", "exchange": "NASD"},
    {"symbol": "ADP", "name": "Automatic Data Processing", "exchange": "NASD"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "exchange": "NASD"},
    {"symbol": "WDAY", "name": "Workday Inc.", "exchange": "NASD"},
    {"symbol": "SPLK", "name": "Splunk Inc.", "exchange": "NASD"},
    {"symbol": "TEAM", "name": "Atlassian Corporation", "exchange": "NASD"},
    {"symbol": "ZEN", "name": "Zendesk Inc.", "exchange": "NASD"},
    {"symbol": "OKTA", "name": "Okta Inc.", "exchange": "NASD"},
    {"symbol": "SPLK", "name": "Splunk Inc.", "exchange": "NASD"},
    {"symbol": "WDAY", "name": "Workday Inc.", "exchange": "NASD"},
    {"symbol": "VMW", "name": "VMware Inc.", "exchange": "NASD"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "exchange": "NASD"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "exchange": "NASD"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "exchange": "NASD"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "exchange": "NASD"},
    {"symbol": "TEAM", "name": "Atlassian Corporation", "exchange": "NASD"},
    {"symbol": "ZM", "name": "Zoom Video Communications", "exchange": "NASD"},
    {"symbol": "DOCU", "name": "DocuSign Inc.", "exchange": "NASD"},
    {"symbol": "TWLO", "name": "Twilio Inc.", "exchange": "NASD"},
    {"symbol": "SNOW", "name": "Snowflake Inc.", "exchange": "NASD"},
    {"symbol": "DDOG", "name": "Datadog Inc.", "exchange": "NASD"},
    {"symbol": "CRWD", "name": "CrowdStrike Holdings", "exchange": "NASD"},
    {"symbol": "ZS", "name": "Zscaler Inc.", "exchange": "NASD"},
    {"symbol": "NET", "name": "Cloudflare Inc.", "exchange": "NASD"},
    {"symbol": "OKTA", "name": "Okta Inc.", "exchange": "NASD"},
    {"symbol": "HUBS", "name": "HubSpot Inc.", "exchange": "NASD"},
    {"symbol": "SPLK", "name": "Splunk Inc.", "exchange": "NASD"},
    {"symbol": "WDAY", "name": "Workday Inc.", "exchange": "NASD"},
    {"symbol": "VEEV", "name": "Veeva Systems Inc.", "exchange": "NASD"},
    {"symbol": "BILL", "name": "Bill.com Holdings", "exchange": "NASD"},
    {"symbol": "SMAR", "name": "Smartsheet Inc.", "exchange": "NASD"},
    {"symbol": "DOCU", "name": "DocuSign Inc.", "exchange": "NASD"},
    {"symbol": "TWLO", "name": "Twilio Inc.", "exchange": "NASD"},
    {"symbol": "MIME", "name": "Mimecast Limited", "exchange": "NASD"},
    {"symbol": "FSLY", "name": "Fastly Inc.", "exchange": "NASD"},
    {"symbol": "ESTC", "name": "Elastic N.V.", "exchange": "NASD"},
    {"symbol": "DBX", "name": "Dropbox Inc.", "exchange": "NASD"},
    {"symbol": "BOX", "name": "Box Inc.", "exchange": "NASD"},
    {"symbol": "ZEN", "name": "Zendesk Inc.", "exchange": "NASD"},
    {"symbol": "SHOP", "name": "Shopify Inc.", "exchange": "NASD"},
    {"symbol": "WIX", "name": "Wix.com Ltd.", "exchange": "NASD"},
    {"symbol": "SQ", "name": "Block Inc.", "exchange": "NASD"},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc.", "exchange": "NASD"},
    {"symbol": "HOOD", "name": "Robinhood Markets Inc.", "exchange": "NASD"},
    {"symbol": "AFRM", "name": "Affirm Holdings Inc.", "exchange": "NASD"},
    {"symbol": "UPST", "name": "Upstart Holdings Inc.", "exchange": "NASD"},
    {"symbol": "SOFI", "name": "SoFi Technologies Inc.", "exchange": "NASD"},
    {"symbol": "RBLX", "name": "Roblox Corporation", "exchange": "NASD"},
    {"symbol": "DIS", "name": "Walt Disney Company", "exchange": "NASD"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "exchange": "NASD"},
    {"symbol": "T", "name": "AT&T Inc.", "exchange": "NASD"},
    {"symbol": "VZ", "name": "Verizon Communications", "exchange": "NASD"},
    {"symbol": "TMUS", "name": "T-Mobile US Inc.", "exchange": "NASD"},
    {"symbol": "CHTR", "name": "Charter Communications", "exchange": "NASD"},
    {"symbol": "EA", "name": "Electronic Arts Inc.", "exchange": "NASD"},
    {"symbol": "TTWO", "name": "Take-Two Interactive", "exchange": "NASD"},
    {"symbol": "ATVI", "name": "Activision Blizzard Inc.", "exchange": "NASD"},
    {"symbol": "NTES", "name": "NetEase Inc.", "exchange": "NASD"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "exchange": "NASD"},
    {"symbol": "PARA", "name": "Paramount Global", "exchange": "NASD"},
    {"symbol": "WBD", "name": "Warner Bros Discovery", "exchange": "NASD"},
    {"symbol": "AMC", "name": "AMC Entertainment Holdings", "exchange": "NASD"},
    {"symbol": "CNK", "name": "Carnival Corporation", "exchange": "NASD"},
    {"symbol": "RCL", "name": "Royal Caribbean Cruises", "exchange": "NASD"},
    {"symbol": "NCLH", "name": "Norwegian Cruise Line", "exchange": "NASD"},
    {"symbol": "MAR", "name": "Marriott International", "exchange": "NASD"},
    {"symbol": "HLT", "name": "Hilton Worldwide Holdings", "exchange": "NASD"},
    {"symbol": "H", "name": "Hyatt Hotels Corporation", "exchange": "NASD"},
    {"symbol": "EXPE", "name": "Expedia Group Inc.", "exchange": "NASD"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "exchange": "NASD"},
    {"symbol": "ABNB", "name": "Airbnb Inc.", "exchange": "NASD"},
    {"symbol": "DAL", "name": "Delta Air Lines Inc.", "exchange": "NASD"},
    {"symbol": "UAL", "name": "United Airlines Holdings", "exchange": "NASD"},
    {"symbol": "AAL", "name": "American Airlines Group", "exchange": "NASD"},
    {"symbol": "LUV", "name": "Southwest Airlines Co.", "exchange": "NASD"},
    {"symbol": "ALK", "name": "Alaska Air Group Inc.", "exchange": "NASD"},
    {"symbol": "SAVE", "name": "Spirit Airlines Inc.", "exchange": "NASD"},
    {"symbol": "JBLU", "name": "JetBlue Airways Corp.", "exchange": "NASD"},
    {"symbol": "BA", "name": "Boeing Company", "exchange": "NASD"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "exchange": "NASD"},
    {"symbol": "RTX", "name": "RTX Corporation", "exchange": "NASD"},
    {"symbol": "NOC", "name": "Northrop Grumman Corp.", "exchange": "NASD"},
    {"symbol": "GD", "name": "General Dynamics Corporation", "exchange": "NASD"},
    {"symbol": "TXT", "name": "Textron Inc.", "exchange": "NASD"},
    {"symbol": "LHX", "name": "L3Harris Technologies", "exchange": "NASD"},
    {"symbol": "TDG", "name": "TransDigm Group Inc.", "exchange": "NASD"},
    {"symbol": "HII", "name": "Huntington Ingalls Industries", "exchange": "NASD"},
    {"symbol": "AIMC", "name": "Altra Industrial Motion", "exchange": "NASD"},
    {"symbol": "FLS", "name": "Flowserve Corporation", "exchange": "NASD"},
    {"symbol": "ITW", "name": "Illinois Tool Works", "exchange": "NASD"},
    {"symbol": "ROK", "name": "Rockwell Automation", "exchange": "NASD"},
    {"symbol": "PH", "name": "Parker-Hannifin Corporation", "exchange": "NASD"},
    {"symbol": "CMI", "name": "Cummins Inc.", "exchange": "NASD"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "exchange": "NASD"},
    {"symbol": "DE", "name": "Deere & Company", "exchange": "NASD"},
    {"symbol": "AGCO", "name": "AGCO Corporation", "exchange": "NASD"},
    {"symbol": "CNHI", "name": "CNH Industrial N.V.", "exchange": "NASD"},
    {"symbol": "ALG", "name": "Alamo Group Inc.", "exchange": "NASD"},
    {"symbol": "TEX", "name": "Terex Corporation", "exchange": "NASD"},
    {"symbol": "MTW", "name": "Manitowoc Company Inc.", "exchange": "NASD"},
    {"symbol": "CARR", "name": "Carrier Global Corporation", "exchange": "NASD"},
    {"symbol": "OTIS", "name": "Otis Worldwide Corporation", "exchange": "NASD"},
    {"symbol": "FAST", "name": "Fastenal Company", "exchange": "NASD"},
    {"symbol": "PCAR", "name": "PACCAR Inc.", "exchange": "NASD"},
    {"symbol": "ODFL", "name": "Old Dominion Freight Line", "exchange": "NASD"},
    {"symbol": "SAIA", "name": "Saia Inc.", "exchange": "NASD"},
    {"symbol": "WERN", "name": "Werner Enterprises Inc.", "exchange": "NASD"},
    {"symbol": "KNX", "name": "Knight Transportation Inc.", "exchange": "NASD"},
    {"symbol": "JBHT", "name": "J.B. Hunt Transport", "exchange": "NASD"},
    {"symbol": "SNDR", "name": "Schneider National Inc.", "exchange": "NASD"},
    {"symbol": "SWFT", "name": "Swift Transportation Co.", "exchange": "NASD"},
    {"symbol": "XPO", "name": "XPO Logistics Inc.", "exchange": "NASD"},
    {"symbol": "CHRW", "name": "C.H. Robinson Worldwide", "exchange": "NASD"},
    {"symbol": "EXPD", "name": "Expeditors International", "exchange": "NASD"},
    {"symbol": "C.H.", "name": "Hub Group Inc.", "exchange": "NASD"},
    {"symbol": "MATX", "name": "Matson Inc.", "exchange": "NASD"},
    {"symbol": "SBLK", "name": "Star Bulk Carriers Corp.", "exchange": "NASD"},
    {"symbol": "GNK", "name": "Genco Shipping & Trading", "exchange": "NASD"},
    {"symbol": "DRYS", "name": "DryShips Inc.", "exchange": "NASD"},
    {"symbol": "GML", "name": "Gulfmark Offshore Inc.", "exchange": "NASD"},
    {"symbol": "TOPS", "name": "TOP Ships Inc.", "exchange": "NASD"},
]


class USStockScanner:
    def __init__(self, auth, base_url: str, logger=None):
        self.auth = auth
        self.base_url = base_url
        self.logger = logger or logging.getLogger(__name__)

    async def scan(
        self,
        top_n: int = 30,
        exchanges: Optional[List[str]] = None,  # type: ignore[assignment]
        min_price: float = 5.0,
    ) -> List[str]:
        exchanges = exchanges or ["NASD", "NYSE"]

        candidates = await self._try_kis_scan(exchanges)
        if candidates:
            filtered = self._filter_by_price(candidates, min_price)
            return filtered[:top_n]

        return self._get_popular_fallback(top_n, exchanges, min_price)

    async def _try_kis_scan(self, exchanges: List[str]) -> Optional[List[Dict]]:
        try:
            import aiohttp

            url = f"{self.base_url}/uapi/overseas-stock/v1/quotations/search"

            headers = self.auth.auth_headers()
            headers["tr_id"] = "HHHPSTK_und_search"
            headers["custtype"] = "P"

            params = {
                "AUTH": "",
                "EXCD": exchanges[0] if exchanges else "NASD",
                "GB": "1",
                "MT": "0",
                "KEYWORD": "",
            }

            async with aiohttp.ClientSession() as session:
                async with session.get(
                    url, params=params, headers=headers, timeout=10
                ) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        if data.get("rt_cd") == "0":
                            return data.get("output", [])

            return None
        except Exception as e:
            self.logger.warning(f"KIS US scan failed, using fallback: {e}")
            return None

    def _filter_by_price(self, stocks: List[Dict], min_price: float) -> List[str]:
        filtered = []
        for stock in stocks:
            try:
                price = float(stock.get("last", 0) or stock.get("lastxch", 0))
                if price >= min_price:
                    filtered.append(stock.get("symbol", stock.get("pdno", "")))
            except (ValueError, TypeError):
                continue
        return filtered

    def _get_popular_fallback(
        self,
        top_n: int,
        exchanges: List[str],
        min_price: float,
    ) -> List[str]:
        filtered = [
            s["symbol"] for s in POPULAR_US_STOCKS if s["exchange"] in exchanges
        ]
        random.shuffle(filtered)
        return filtered[:top_n]

    def get_all_popular_stocks(self) -> List[Dict]:
        return POPULAR_US_STOCKS.copy()

    def get_stocks_by_exchange(self, exchange: str) -> List[str]:
        return [s["symbol"] for s in POPULAR_US_STOCKS if s["exchange"] == exchange]
